apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    deployment: {{ .Values.registry.name }}
  ports:
  - port: 5000
    targetPort: 5000