patch:
  namespace: gp-infrastructure
  serviceAccountRef: patch-operator-sa
sonarqube:
  updateStrategy:
    type: Recreate
  sonarqubeUsername: "admin"
  sonarqubePassword: "admin"
  service:
    type: ClusterIP
    extraPorts:
      - name: oauth-proxy
        port: 9091
        protocol: TCP
        targetPort: 9091
  ingress:
    enabled: false
    hostname: "sonar.apps.play.gepaplexx.com"
  persistence:
    enabled: true
  postgresql:
    auth:
      password: "changeme"
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    volumePermissions:
      enabled: false
  rbac:
    create: true
  serviceAccount:
    create: true
    name: sonarqube  #CANNOT BE CHANGED, OTHERWISE OAUTH WON'T WORK!
    automountServiceAccountToken: true
  metrics:
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true

# OAUTH Gschichten
  extraVolumes:
    - name: ocp-injected-certs
      configMap:
        name: ocp-injected-certs
    - name: sonarqube-proxy
      secret:
        secretName: sonarqube-proxy
    - name: sonarqube-tls
      secret:
        secretName: sonarqube-tls
  extraEnvVarsCM: sonarqube-extra-env-config
  sidecars:
    - args:
        - '-provider=openshift'
        - '-pass-basic-auth=true'
        - '-https-address=:9091'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9000'
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'  # jeder der Namespaces lesen darf, darf sich einloggen
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}' # jeder der Namespaces lesen darf, darf sich einloggen
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-openshift-service-account=sonarqube'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-openshift-ca=/etc/sonarqube-configmaps/ocp-injected-certs/ca-bundle.crt'
        - '-skip-auth-regex=(^/metrics|^/batch|^/api)'
      image: 'quay.io/openshift/origin-oauth-proxy'
      name: sonarqube-proxy
      ports:
        - containerPort: 9091
          name: oauth-proxy
      resources:
        requests:
          cpu: 1m
          memory: 20Mi
      volumeMounts:
        - mountPath: /etc/tls/private
          name: sonarqube-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: sonarqube-proxy
          readOnly: false
        - mountPath: /etc/sonarqube-configmaps/ocp-injected-certs/
          name: ocp-injected-certs
          readOnly: true