apiVersion: v1
kind: ServiceAccount
metadata:
  name: testresults
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"testresult-publisher"}}
automountServiceAccountToken: true