apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: {{ .Release.Namespace }}
  labels:
    operators.coreos.com/grafana-operator.openshift-monitoring: ''
spec:
  channel: "{{ .Values.subscription.channel }}"
  installPlanApproval: "{{ .Values.subscription.installPlanApproval }}"
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v4.5.0
  config:
    env:
      - name: DASHBOARD_NAMESPACES_ALL
        value: "true"
