patchOperator:
  namespace: gp-infrastructure
  serviceAccount: patch-operator-sa

kasten:
  clusterName: "example"
  auth:
    groups: ["Gepaplexx"]
    clusterApiURL: "api.example.gepaplexx.com"
    openshift:
      enabled: true
    serviceAccountName: "kasten-dex-sa"
  serviceAccount:
    create: true
    name: "kasten-sa"
  route:
    host: "kasten.apps.example.gepaplexx.com"
  backuplocation:
    enabled: true
    size: 150Gi
    claimName: "kasten-backup-location"
    storageclass: nfs-client