project:
  create: true
  name: example

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: false
    destination:
      namespace: openshift-operators
      create: false
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: false
    destination:
      namespace: openshift-gitops
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################### VELERO ############################
  velero:
    name: velero
    enabled: false
    destination:
      namespace: velero
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
      helm:
        parameters:
          - name: configuration.backupStorageLocation.bucket
            value: "" # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.region
            value: minio # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.s3Url
            value: "" # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH ##########################
  rookCeph:
    name: rook-ceph
    enabled: false
    destination:
      namespace: rook-ceph
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################### CLUSTER-LOGGING OPERATOR ##########################
  clusterLoggingOperator:
    name: cluster-logging-operator
    enabled: false
    destination:
      namespace: openshif-logging
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging
    enabled: false
    destination:
      namespace: openshift-logging
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: false
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: ""
      path: ""
      targetRevision: ""
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# TODO certificates/*, registries/*, secret-store/*???,
# TODO Operators: jaeger, oauth-group-sync, pipelines, postgres