project:
  create: true
  name: example

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: false
    destination:
      namespace: openshift-operators
      create: false
    source:
      chart: resource-locker-operator
      repoURL: https://redhat-cop.github.io/resource-locker-operator
      targetRevision: 1.*
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: false
    destination:
      namespace: openshift-gitops
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-identity-provider
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-oauth-group-sync
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-config
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-updater
      helm:
        parameters:
        - name: "slack.channel"
          value: "" #TODO
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################### VELERO ############################
  velero:
    name: velero
    enabled: false
    destination:
      namespace: velero
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-velero
      helm:
        parameters:
          - name: configuration.backupStorageLocation.bucket
            value: steppe.gepaplexx.com # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.region
            value: minio # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.s3Url
            value: http://10.20.26.100:9000 # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: false
    destination:
      namespace: rook-ceph
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-storage-ceph-operator
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH INSTANCE ##########################
  rookCephInstance:
    name: rook-ceph-instance
    enabled: false
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-storage-cephcluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################### CLUSTER-LOGGING OPERATOR ##########################
  clusterLoggingOperator:
    name: cluster-logging-operator
    enabled: false
    destination:
      namespace: openshif-logging
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-operator
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: false
    destination:
      namespace: openshift-logging
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      chart: gp-cluster-logging-instance
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: false
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### OPENSHIFT PIPELINES OPERATOR ######################
  openshiftPipelinesOperator:
    name: openshift-pipelines-operator
    enabled: false
    destination:
      namespace: openshift-gitops
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-tekton-operator
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: false
    destination:
      namespace: openshift-image-registry
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: false
    destination:
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-pull-through-cache
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-certificates-patches
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: false
    destination:
      namespace: example
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-issuer
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# Future-TODO: secret-store/HashiCorp-Valult, tekton instanz (openshift pipeline)