apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: template-image-operations
spec:
  serviceAccountName: builder
  templates:
  - container:
      args:
      - --dockerfile={{ inputs.parameters.containerfile }}
      - --context=/mnt/out/{{ inputs.parameters.reponame }}
      - --destination=image-registry.openshift-image-registry.svc.cluster.local:5000/{{
        inputs.parameters.namespace }}/{{ inputs.parameters.reponame }}:{{ inputs.parameters.tag
        }}
      - --skip-tls-verify
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
      - mountPath: /mnt/out/
        name: workspace
      - mountPath: /kaniko/.docker
        name: dockerconfig
    inputs:
      parameters:
      - name: tag
      - name: namespace
      - name: reponame
      - name: containerfile
    metadata:
      labels:
        app: argo
        clusterWorkflowTemplate: template-image-operations
        template: kanio-image-build
    name: kaniko-image-build
    volumes:
    - name: dockerconfig
      secret:
        items:
        - key: .dockerconfigjson
          path: config.json
        secretName: builder-dockerconfig
