{{- if .Values.htpasswd.enable  }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.htpasswd.k8secretName }}
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: {{ .Values.htpasswd.data }}
  template:
    metadata: {}
{{- end }}
