{{- if .Values.htpasswd.enable  }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.htpasswd.k8secretName }}
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: {{ .Values.htpasswd.data }}
  template:
    metadata: {}
---
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswd.k8secretName }}
  namespace: openshift-config
stringData:
  default: "true"
{{- end }}
