{{- if .Values.ldap.enable  }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ldap.k8secretName }}
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: {{ .Values.ldap.bindPassword }}
    bindDn: {{ .Values.ldap.bindDn }}
    ldapUrl: {{ .Values.ldap.ldapUrl }}
  template:
    data:
      groupsQuery: {{ .Values.ldap.groupsQuery }}
    metadata: {}
---
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ldap.k8secretName }}
  namespace: openshift-config
stringData:
  default: "true"
{{- end }}
