{{- if .Values.ldap.enable }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
  - apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-group-syncer
subjects:
  - kind: ServiceAccount
    name: ldap-group-syncer
    namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-group-syncer
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
data:
  sync.yaml: ""
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-ldap-sync-cm
  namespace: gp-infrastructure
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-ldap-sync-cm:
      patchTemplate: |
        data:
          sync.yaml: |
            kind: LDAPSyncConfig
            apiVersion: v1
            url: {{`"{{ (index . 1).data.ldapUrl | b64dec }}"`}}
            insecure: true
            bindDN: {{`"{{ (index . 1).data.bindDn | b64dec }}"`}}
            bindPassword:
              file: "/etc/secrets/bindPassword"
            groupUIDNameMapping:
              {{- range $key, $val := .Values.ldap.groupMappings }}
              {{ $key }}: {{ $val }}
              {{- end }}
            activeDirectory:
              usersQuery:
                baseDN: {{`"{{ (index . 1).data.usersQuery | b64dec }}"`}}
                scope: sub
                derefAliases: never
                filter: {{ .Values.ldap.syncFilter | default "(objectClass=person)" }}
                pageSize: 0
              userNameAttributes: [ cn ]
              groupMembershipAttributes: [ memberOf ]
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: ldap-group-syncer
        namespace: openshift-config
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: {{ .Values.ldap.k8secretName }}
          namespace: openshift-config
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800
      template:
        spec:
          containers:
            - name: ldap-group-sync
              image: "registry.redhat.io/openshift4/ose-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync --sync-config=/etc/config/sync.yaml --confirm"
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-syncer"
            - name: "ldap-bind-password"
              secret:
                secretName: "ldap-secret"
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-pruner
  namespace: openshift-config
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800
      template:
        spec:
          containers:
            - name: ldap-group-pruner
              image: "registry.redhat.io/openshift4/ose-cli:latest"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups prune --sync-config=/etc/config/sync.yaml --confirm "
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-syncer"
            - name: "ldap-bind-password"
              secret:
                secretName: "ldap-secret"
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"
{{- end }}
