{{- if .Values.ldap.enable  }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ldap.k8secretName }}
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: {{ .Values.ldap.bindPassword }}
    bindDn: {{ .Values.ldap.bindDn }}
    ldapUrl: {{ .Values.ldap.ldapUrl }}
    groupsQuery: {{ .Values.ldap.groupsQuery }}
    usersQuery: {{ .Values.ldap.usersQuery }}
  template:
    metadata: {}
{{- end }}
