# https://github.com/redhat-cop/patch-operator/issues/26
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-identity-prov
  namespace: gp-infrastructure
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-identity-prov:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
{{- if .Values.git.enable }}
            - name: Gepaplexx
              mappingMethod: claim
              type: GitHub
              github:
                clientID: {{`"{{ (index . 1).data.clientId | b64dec }}"`}}
                organizations: {{`{{ (index . 1).data.restrOrgs | b64dec }}`}}
                clientSecret:
                  name: {{ .Values.git.k8secretName }}
{{ end }} {{ if .Values.google.enable }}
            - name: Gepardec
              mappingMethod: claim
              type: Google
              google:
                clientID: {{`"{{ (index . 2).data.clientId | b64dec }}"`}}
                hostedDomain: {{`"{{ (index . 2).data.restrDomain | b64dec }}"`}}
                clientSecret:
                  name: {{ .Values.google.k8secretName }}
{{ end }}  {{ if .Values.ldap.enable }}
            - name: Ldap
              mappingMethod: claim
              type: LDAP
              ldap:
                attributes:
                  id:
                    - dn
                  email:
                    - mail
                  name:
                    - cn
                  preferredUsername:
                    - cn
                    - uid
                bindDN: {{`"{{ (index . 3).data.bindDn | b64dec }}"`}}
                bindPassword:
                  name: {{ .Values.ldap.k8secretName }}
                insecure: true
                url: {{`"{{ (index . 3).data.ldapUrl | b64dec }}"`}}
{{ end }} {{ if .Values.htpasswd.enable }}
            - name: HTPasswd
              mappingMethod: claim
              type: HTPasswd
              htpasswd:
                fileData:
                  name: {{ .Values.htpasswd.k8secretName }}
{{ end }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        name: {{ .Values.git.k8secretName }}
        namespace: openshift-config
      - apiVersion: v1
        kind: Secret
        name: {{ .Values.google.k8secretName }}
        namespace: openshift-config
      - apiVersion: v1
        kind: Secret
        name: {{ .Values.ldap.k8secretName }}
        namespace: openshift-config
