{{ if or .Values.git.enable .Values.google.enable .Values.htpasswd.enable }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-identity-prov
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-identity-prov:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
{{- if .Values.git.enable }}
            - name: Gepaplexx
              mappingMethod: claim
              type: GitHub
              github:
                clientID: {{`"{{ (index . 1).data.clientId | b64dec }}"`}}
                organizations: {{`"{{ (index . 1).data.restrOrgs | b64dec }}"`}}
                clientSecret:
                  name: {{ .Values.git.k8secretName }}
{{ end }} {{ if .Values.google.enable }}
            - name: Gepardec
              mappingMethod: claim
              type: Google
              google:
                {{- if not .Values.git.enable }}
                clientID: {{`"{{ (index . 1).data.clientId | b64dec }}"`}}
                hostedDomain: {{`"{{ (index . 1).data.restrDomain | b64dec }}"`}}
                {{- else }}
                clientID: {{`"{{ (index . 2).data.clientId | b64dec }}"`}}
                hostedDomain: {{`"{{ (index . 2).data.restrDomain | b64dec }}"`}}
                {{- end }}
                clientSecret:
                  name: {{ .Values.google.k8secretName }}
{{ end }} {{ if .Values.htpasswd.enable }}
            - name: HTPasswd
              mappingMethod: claim
              type: HTPasswd
              htpasswd:
                fileData:
                  name: {{ .Values.htpasswd.k8secretName }}
{{ end }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
  {{- if .Values.git.enable }}
      - apiVersion: v1
        kind: Secret
        name: {{ .Values.git.k8secretName }}
        namespace: openshift-config
  {{- end }} {{ if .Values.google.enable }}
      - apiVersion: v1
        kind: Secret
        name: {{ .Values.google.k8secretName }}
        namespace: openshift-config
  {{ end }}
{{ end }}