apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-identity-prov
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
{{- if .Values.git.enable }}
    patch-identity-prov-gepaplexx:
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: {{ .Values.git.k8secretName }}
          namespace: openshift-config
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
            - name: Gepaplexx
              mappingMethod: claim
              type: GitHub
              github:
                clientID: {{`"{{ (index . 1).data.clientId | b64dec }}"`}}
                organizations: {{`{{ (index . 1).data.restrOrgs | b64dec }}`}}
                clientSecret:
                    name: {{ .Values.git.k8secretName }}
  {{end}}
  {{- if .Values.google.enable }}
    patch-identity-prov-gepardec:
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: {{ .Values.google.k8secretName }}
          namespace: openshift-config
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
            - name: Gepardec
              mappingMethod: claim
              type: Google
              github:
                clientID: {{`"{{ (index . 1).data.clientId | b64dec }}"`}}
                hostedDomain: {{`{{ (index . 1).data.restrOrgs | b64dec }}`}}
                clientSecret:
                  name: {{ .Values.google.k8secretName }}
  {{end}}
  {{ if .Values.htpasswd.enable}}
    patch-identity-prov-htpasswd:
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
            - name: HTPasswd
              mappingMethod: claim
              type: HTPasswd
              htpasswd:
                fileData:
                  name: htpass-secret
  {{end}}
  {{ if .Values.ldap.enable}}
    patch-identity-prov-ldap:
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: {{ .Values.ldap.k8secretName }}
          namespace: openshift-config
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: OAuth
        name: cluster
      patchTemplate: |
        spec:
          identityProviders:
            - name: Ldap
              mappingMethod: claim
              type: Ldap
              ldap:
                attributes:
                  id:
                    - dn
                  email:
                    - mail
                  name:
                    - cn
                  preferredUsername:
                    - uid
                bindDn: {{`"{{ (index . 1).data.bindDn | b64dec }}"`}}
                bindPassword:
                  name: {{ .Values.ldap.k8secretName }}
                insecure: true
                url: {{`"{{ (index . 1).data.ldapUrl | b64dec }}"`}}
  {{end}}