apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: label-openshift-config-ns-patch
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    label-openshift-config-ns-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Namespace
        name: openshift-config
      patchTemplate: |
        metadata:
          labels:
            argocd.argoproj.io/managed-by: {{ .Release.Namespace }}
      patchType: application/merge-patch+json