apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  configMaps:
    - grafana-oauth-config
  ingress:
    enabled: true
    pathType: Prefix
    path: "/"
    hostname: {{ .Values.ingress.hostname }}
  config:
    auth:
      disable_login_form: False
      disable_signout_menu: False
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    log.frontend:
      enabled: true
    security:
      admin_user: {{ default "admin" .Values.auth.admin.user }}
  dashboardLabelSelector:
    - matchExpressions:
        - key: dashboard
          operator: In
          values:
            - system
            - application