# TODO: values für clientSecret und urls setzen in values-play.yaml. Testen.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "grafana-sso-config"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    clientsecret: {{ .Values.sso.keycloak.clientSecret }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: grafana-sso-patch
  namespace: {{ .Release.Namespace }}
spec:
  patches:
    grafana-sso-patch:
      patchTemplate: |
        spec:
          auth.generic_oauth:
            client_secret: {{`"{{ (index . 1).data.clientsecret }}"`}}
      targetObjectRef:
        apiVersion: integreatly.org/v1alpha1
        kind: Grafana
        namespace: {{ .Release.Namespace }}
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          namespace: {{ .Release.Namespace }}

