# TODO: values für clientSecret und urls setzen in values-play.yaml. Testen.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "grafana-sso-config"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    clientsecret: {{ .Values.sso.keycloak.clientSecret }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: grafana-sso-patch
  namespace: gp-infrastructure
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    grafana-sso-patch:
      patchTemplate: |
        spec:
          config:
            auth.generic_oauth:
              client_secret: {{`"{{ (index . 1).data.clientsecret | b64dec }}"`}}
      targetObjectRef:
        apiVersion: integreatly.org/v1alpha1
        kind: Grafana
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          namespace: {{ .Release.Namespace }}
          name: "grafana-sso-config"
      patchType: application/merge-patch+json
