apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ots
    {{- include "gp-one-time-secret.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
  {{- end }}
  tls:
    termination: edge
  to:
    kind: Service
    name: ots
    weight: 100
  wildcardPolicy: None
