kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
  volumeMode: Filesystem
