{{- if .Values.argocd.addWorkflowRepository-}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workflow-repository
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    sshPrivateKey: {{ .Values.argocd.workflowRepository.sshPrivateKey }}
    username: {{ .Values.argocd.workflowrepository.username }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: workflow-repository
      namespace: {{ .Release.Namespace }}
{{- end -}}