apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gepaplexx-cicd-tools-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.sealedSecrets.postgresql.password }}
    postgres-password: {{ .Values.sealedSecrets.postgresql.postgresPassword }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gepaplexx-cicd-tools-postgresql
      namespace: {{ .Release.Namespace }}
