{{- if .Values.argo_workflows.archive.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-anyuid-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: {{ .Values.minio.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-artifact-repository
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    secretkey: {{ .Values.argo_workflows.archive.secretkey }}
  template:
    data:
      accesskey: minio
    metadata:
      creationTimestamp: null
      name: minio-artifact-repository
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}