project:
  create: true
  name: gepaplexx

applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-resource-locker
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-identity-provider
      targetRevision: "*"
      helm:
        parameters:
        - name: "google.clientSecret"
          value: "AgBmfZpbfdNP9NJwAOaNcWND1FDRQYxS5h+bdUVZ4RUQTewqiTVKrEY/z9CZd324IfHZwhsPWyLpKaeJDIATG/OwnSl+1dKfy+4mTMsnG8gdgRhbOD+TL0aJ8bHDeDdTXn+v9F0m0B5n0kS4OnIi9O9AFYS4CVtnxj60ong4oHugmQSw0HBPxrvAywLtMrpyoZW53/nxfhRBGGE3gNdXGeH4j+IXzI+/joOUw2bOOFeDh8TGK1patkpX2oYO7K/DI3gYWBYj/R4H6frPt7DG6GxLmkEvtLfKYZTY4/dRzVxHzVwDsojFB1ZIoNxdX/S8fSHRAuc4R3Y/QXsV6QUHm1B1sp+a1VC2RLjAtHXeeBwYOgLi+mUcV7Y4MidS43m+UMrhedWfN0a6OLkDrQ+SilA7iFgLDhlAzKO7CWtP9pbk2AouVmx0gT+fIZX3xJp5CRKEDY4q5SFIxaK7ynfVXdxuVthiRVQN8rZ0mCLBH3GLtQs/vVlUDZRQ1+0GGOD3BS7bzyneHStCpxMvn3d36pZRU30UtULdKczHOAPp/cFjrLv1SEQX1pbPt8lgShnypEuChSaZzbQ5Fzdst7PFMlSrRD+6+Vdet/qPVyXfF5ZK/QZqvX11yDsUXtmkWjmwsaMpsB3AwmdIE7RtFGQuLCn5Cc3JQptqjkGL8f1qlftgRNcR/LGYt8Q6CCSXQdXgHCEopZnxalfOQcah8VCsRE3VFUHpHLmQFsmi5dLkW+K000JoxQ=="
        - name: "google.clientId"
          value: "AgCfiYeLi/1R/27oLVqiaEuRbh1Gd+YVRswbV2a37k+YIlUgaVSfxJvMCWJpA4xBOnsyXeUMXw+YHb3IOPCNEHxU3nDBYGxu8CTIvtM7/O4xw9PSn2re+sOrWPWYpsezIdw2nIBjSTFFwQcDwIhr427FImq7M+qTDNTMcvYem/C+KzkUWWhGr8KY4KO7yv7dwFGNTAuF9Qcdf0T0RCjFAOfWxExKLXXOXc6OTnhNTiUCUXGPSHAyxhKo4TEj7dOIh6Uq4J3GQlutxhiXeAcAasaCyMKgDRMzUc26JGNRA8gUxixFfKDBuXlcD2TTzox+Is3ai49D7g69q0JfURlBEUOBAecpwrfKx5fg8kBy+3NagjUGNDEeVuPycc/E9vw/AUSNCVDJGPADv10a7rN9mMD8JX6uh7NuIbCyJqedJWKDOZ7qynjC7KQqHHzXyZz9NkO9nWnDu5VwdnziftW7xjEtzR3OF3k8+B5v8D1KDnHXZt93N+uNkcCPvvkeCHqRemoEkOgejNJz8V4JDrJH27diiVVqZsMnv0B6IgRP+ocp/9rVpzgq9MXFIsPsUY60gfRkULbPQHk1fVrfqujUIdNZYnA0tTfY2DsGS90AjrVsnPms6hETdiQ8BZpkr46qwXM7nzdAlb5BKrf4J6F7DknzvKWDr2BqXOweYbqeUlpaLb7zBnzuKuzxQSroN9+2onOq5k+XhgWVciBR0ZVSHIxpPvXIWo8SLVMWco0URB2KBIeCsI1Zz7u1zaKtvPjU2p/gG9NRB8jJz25yatA2HGSckAkaqq8nBnA="
        - name: "google.restrDomain"
          value: "AgBRqnwzLaiwKaIbnVrfv2RxYKWsf2wQLFDWrwK+vD+v1zAzfOmPNjoavIyq0qJbndqHbWlnbB5h1sko1VdIs/xeWBzKwKaEVNDFkRZ3GC5zNdTRD1mJtzYzGbrFfG0X7FdW6+CtTbbv1s+qn3thCqIAX7+PBPoZ5Okf+QctuPaXyAfXDetcXUMLssPBD7jd/sUR3yeX3ipDzNT8rPOcq92oac9kMiWfnKLOm5To+PkAlMO2vMUygNK4vOB3vdWgFmXOdn2wskdDSqaaoGzU2dljLc8YMceh28LL5HpfE+1BKudOGgwYmZcjPp+cP6hARopIvkHI61votzEiCJIAFdHrF7tex1PLUa++oYTNh6i5zXQPdXDS/jteSq5CM1XzrdXzs54hsm0b4KbS1zDaZe6qUgT5Rk3jaYMaYJdgymciXnBkYGLiMd3nylW9T4wk/1kSEl7b1ZMBiYYcNEo9Az5hDNYKUBcDf/AUXnMEFeE8OC8yXCZUShB4JJAM/54CQq/IuX1X4XdTRdYa/1oQOQ7/AaivLGWK94a1vMqBVviFsm/xzjrNthtJbpyjT8UGn+8qivxnWqJCyxX4hvuaKb6PArFIb8vW82tHimga+9NG6bIhsVXBn1P7VGw8sZ6f7Fw4xyroJXfcKKdOAwIV6Q5wgdlL2a/nvzxte0/pYYvNOyueeR0IIdvEqjkva6HniPCDcLZpgp3ALFDWnWxN"
        - name: "git.clientSecret"
          value: "AgB0EhaayJY5RWvYV94fWnHjx/bIvGzTjEO34PhqcMYh03QSXGYDK5iRIfNol8nXcsHPgGxqzM1/oXbvC0l/+vKE1T8o35X8L48ifqVXLaA1ImmM5TvesnnKXLUCgw8Yy5ZEJTv957KEbW/SphxZuXJIo/uiy4NQNPLBFtZ2oiMcPaBIrMImC13NWG5yet/QIFXevxag4GcMpP9B4hfGEH+xYIY4QgRuaWl96CxNsVFxJzWnKLT1APYNYTwUU0tH4KSCs3F6HkAYvts4OTPvvJ0BL05iXKtoky6EJ2H6+Fl/RMQVliCCi0FrePq1Qv7PwXNifcIYCBxl3Y3kXcWAV5CrmsGqy4N3RXRwbiJ2gLaUUwLCNgaFFUPzNoEBz6uPg0P3dO3ogoyiJwtiNQ6bonDyfmyDqytveaQZFMzrkmRMHkwRALUF7BV4I6+Ers7aYee9BKsfJNDQt26yWkLM745ul5BBmg5M0rFipX1zrGzW2ZFumFSbs3OVbBXOEgBME1H7+QOiWdIVbCKLI3HbCPSPj5kIY/UC4FIxgZdPBdXfshcqgU2egD9M4pEAkUJxQT2LelhKZEKZRk2KrcxK0Gil/f5BVe4RpOZHlqWJLte+7P3n5qVakjPLN++CNBwfjKhdJA62w6/R8RZ/zAbIz4XkPBWZiiFRaDPFapjl1rWlmeaeEWLKfkLnkKw/M9Rjfa0Go5nfSEyNapplHP5g6UpXlp1tHEBATAgUQf/Yp9GnV+FoQUI="
        - name: "git.clientId"
          value: "AgAtIFyqJNnmoG+AwWVJgdkkoU6ztqh/tB4juIAo/q3h9S5b59Zev8m9nHjv2kAnd9WwwBcNcqi0PqvZIa44UBN7XAPeoUGsHv9cNW6b0hht8LI3oJrt/zASZnifxyAMiuoQ3FX9H2JtGr0bFjnmMeLc15ccLIlIvW9xr9Wu5skY4AwxdFgAoCr8L+KAWYhZWF+Y4ctC+orK+pDO28KrMVqf+TePyX9S/EvbuIs9y6ETSmRDEIOjnrL3AfScKtYykMDSBbDWIA769B/1oL/LhADmtqWLojltiWbV+1ddqRfrQTYDpMCcn/JIpQKTNA2gY8JwDWO+cjcpug0BnEBXtWy3HekOZQZQ4AFt+8NgQojVdOf6ZR/LcAnUyuir4EJQOPk+WQikFaYZgH80Wy0DHLObrOLjyJbO+uak7jwbwO3l3imxupRTbG8bK3e/bAp+CrJ+y97unsd1zWX2NxbI7XO/HFVAJ7PT2KH3RQBLM76gs7E7D5Ddy//ecqPD0mRrrjDcF9i9fwhgUvj6sxhgog5gfBYmhf2gNIFBzSkIhsYBkeYr5KSrn0HVzVPKOESq7F24fnUWB+KXjGfi76uVXwYArFPNt3PTe3SU7a8965kpF2fGSTPW9hGsCgTH4ObTKNbOh74OuLDu5t+6dOyA6uZV7N1seFFnxDD7IQ3TqlUM8DKiucjwvlB956DGGgl7qseVbLXOHpuF7+fw4BM0oFoDFOVGNQ=="
        - name: "git.restrOrgs"
          value: "AgBulB3F4Al54XRSH2HW+K8u3GcX86FzblXalnndiuYd7ZGJZNKSt03CPfyLxKvUQyyS7kPXGD1E1lxJI1t6O4+W8vmsEZsfunw+ug1q+2dO7wf28MfBD+0on6FO+hhjmKbJq/8l4PF3jAYISMs2QYbDorRQe2Ttphjo5/nWwZBXEH0u613coETJVX+voRA8ER1UFuI+dKxRsUAeZqxfy3BF1+rGR3OqszUqPA8qNJP3OLQEJekpRa5EuoFDIiTtPvhM/lnGdFxLDKfDAq+nCbP5UTmz+m7sb3zxopL2QkWzygOVKdr4XwjykVtNcsxQ7QmRY1Tr/3jmVkYqWslP0lyhXBsVnJYPwPv8vVamO5mvfWxjYOcl0Hh9wIjbxhBKZd+4HG8006l9lqRLBfKAkfeLQUwwYwehdhRrCKNrjP8wQmJk5cB7DaPyfpzl3IBIlRgL+nI6u2pTiHP1S0bajDhaYbekPSUSlJXEr6vjGCcper5i/YcuY+F2bxjw3yxSyVfzFiSz8jnTWo/8+IxDRcTzN/fSPvoLb2ZkJO8znZLe6qtDKfP9z1OD/UNXzVpb5eIFRZSOiJ08h20IMjvKXjZQKqzFtlDWbjnVX1vpdj8DgBYnv8Z8tIomwZtKXdfo7/1Z7EsuzfQEwguF6oBtNtpC58CuZEClGceCy2w2uHP+weWHYfaU8v1z5zTX5cKlBnY0ILzEG7L27gstjXD1+ZpiKXc5mw=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-oauth-group-sync
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-config
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-updater
      targetRevision: "*"
      helm:
        parameters:
        - name: "slack.channel"
          value: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxRk0zQUNES04vQjAxUTI0NkI1TksvMUFIaHlIUlVsOVlVS2c2WHp5UGh2Z3dDCg=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################### VELERO ############################
  velero:
    name: velero
    enabled: false
    destination:
      namespace: velero
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-velero
      targetRevision: "*"
      helm:
        parameters:
          - name: configuration.backupStorageLocation.bucket
            value: prod.gepaplexx.com # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.region
            value: minio # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
          - name: configuration.backupStorageLocation.config.s3Url
            value: http://10.20.26.100:9000 # TODO via ansible vault? => via ResourceLockerPatch und Werte in Secrets (siehen Identity Provider)
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    destination:
      namespace: rook-ceph
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-rook-ceph-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH INSTANCE ##########################
  rookCephInstance:
    name: rook-ceph-instance
    enabled: true
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-storage-cephcluster
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################### CLUSTER-LOGGING OPERATOR ##########################
  clusterLoggingOperator:
    name: cluster-logging-operator
    enabled: true
    destination:
      namespace: openshift-logging
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: true
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### OPENSHIFT PIPELINES OPERATOR ######################
  openshiftPipelinesOperator:
    name: openshift-pipelines-operator
    enabled: true
    destination:
      namespace: openshift-gitops
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-tekton-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    destination:
      namespace: openshift-image-registry
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    destination:
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-pull-through-cache
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-certificates-patches
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-issuer
      targetRevision: "*"
      helm:
        parameters:
        - name: "solvers.dnsZones[0]"
          value: "steppe.gepaplexx.com"
        - name: "solvers.accessKeyId"
          value: "" #TODO
        - name: "solvers.secretAccessKey"
          value: "" #TODO
        - name: "certificates.defaultIngress"
          value: "apps.steppe.example.com"
        - name: "certificates.console"
          value: "steppe.gepaplexx.com"
        - name: "certificates.api"
          value: "api.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# Future-TODO: secret-store/HashiCorp-Valult, tekton instanz (openshift pipeline)