{{- if .Values.kasten.backuplocation.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.kasten.backuplocation.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-kasten-backup.labels" . | nindent 4}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{  .Values.kasten.backuplocation.size }}
  storageClassName: {{ .Values.kasten.backuplocation.storageclass }}
{{- end -}}