apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://{{ .Values.kasten.route.host }}/k10-instance/dex/callback
  labels:
    {{- include "gp-kasten-backup.labels" . | nindent 4}}
  name: {{ .Values.kasten.auth.serviceAccountName }}
  namespace: {{ .Release.Namespace }}