apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "A value for 'argocd.application.name' is required." .Values.argocd.application.name }}
spec:
  destination:
    namespace: {{ default .Release.Namespace .Values.argocd.application.destination.namespace }}
    server: 'https://kubernetes.default.svc'
  project: {{ default "default" .Values.argocd.project.name }}
  source:
    path: {{ .Values.argocd.application.source.chartPath }}
    repoURL: {{ .Values.argocd.application.source.appRepoURL }}
    targetRevision: {{ .Values.argocd.application.source.appRevision }}
    helm:
      valueFiles:
      - {{ .Values.argocd.application.source.valuesYaml }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.application.syncPolicy.prune }}
      selfHeal: {{ .Values.argocd.application.syncPolicy.selfHeal }}
