global:
  nameOverride:

image:
  name: ghcr.io/gepaplexx/gp-oauth-group-sync-operator
  tag: latest

replicas: 1

resources:
  limits:
    cpu: 10m
    memory: 256Mi
  requests:
    cpu: 5m
    memory: 128Mi

  