apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    patch-apiserver:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: APIServer
        name: cluster
      patchTemplate: |
        spec:
          servingCerts:
            namedCertificates:
              - names:
                  - {{ .Values.apiserver.customApiUrl }}
                servingCertificate:
                  name: api-tls
      patchType: application/merge-patch+json