apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-default-ingresscontroller
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-default-ingrescontroller:
      targetObjectRef:
        apiVersion: operator.openshift.io/v1
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
      patchTemplate: |
        spec:
          defaultCertificate:
            name: default-tls
      patchType: application/merge-patch+json