clusterAdminSAName: gp-admin-sa

resourceQuota:
  requests:
    cpu: 3
    memory: 2Gi
  limits:
    cpu: 6
    memory: 5Gi

limitRange:
  default:
    cpu: 50m
    memory: 500Mi
  defaultRequest:
    cpu: 25m
    memory: 250Mi