apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-cephcluster
  namespace: {{ .Values.patchOperator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  serviceAccountRef:
    name: {{ .Values.patchOperator.serviceAccount }}
  patches:
    patch-cephcluster:
      targetObjectRef:
        apiVersion: ceph.rook.io/v1
        kind: CephCluster
        name: {{ .Values.cephcluster.clusterName }}
        namespace: {{ .Release.Namespace }}
      patchTemplate: |
        spec:
          placement:
            mon:
              {{- include "infranodes.enabled" . | nindent 12}}
            mgr:
              {{- include "infranodes.enabled" . | nindent 12}}
      patchType: application/merge-patch+json