apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: gp-eso
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-external-secrets-configuration.labels" . | nindent 4 }}
spec:
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
  certController:
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 100m
  webhook:
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 100m