apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://{{ .Values.kasten.route.host }}/k10-instance/dex/callback
  name: {{ .Values.kasten.auth.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}