apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    kubernetes.io/metadata.name: rook-ceph
    openshift.io/cluster-monitoring: "true"
  name: rook-ceph
spec: {}
