#https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-the-monitoring-stack
infranodes:
  enabled: false

clusterMonitoring:
  enableUserWorkload: true
  prometheusK8s:
    retention: 31d
    resources:
      requests:
        cpu: 300m
        memory: 4Gi
      limits:
        cpu: 1
    storageClassName: rook-ceph-block
    storageSize: 40Gi
  alertmanagerMain:
    resources:
      requests:
        memory: 200Mi
    storageClassName: rook-ceph-block
    storageSize: 10Gi

userWorkloadMonitoring:
  prometheus:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1
    storageClassName: rook-ceph-block
    storageSize: 40Gi
  thanosRuler:
    storageClassName: rook-ceph-block
    storageSize: 10Gi

