apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "http-mirror.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 24Gi
  storageClassName: rook-ceph-fs