apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-ocp-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.role.kind }}
  name: {{ .Values.rbac.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccount.name }}
    namespace: {{ .Values.rbac.serviceAccount.namespace }}
