apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: "{{ .Values.subscription.channel }}"
  installPlanApproval: "{{ .Values.subscription.installPlanApproval }}"
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
        value: "{{ .Values.subscription.disableDefaultInstance }}"