apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/patch-operator.openshift-operators: ""
  name: patch-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      requests:
        memory: 512Mi
        cpu: "100m"
      limits:
        memory: 2Gi
        cpu: "250m"