{{- if .Values.token.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.token.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  token: "{{ .Values.token.apitoken | b64enc }}"
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slack.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  url: {{ .Values.slack.url | b64enc }}