apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-mirror.fullname" . }}-config
data:
  default.conf: |-
    proxy_cache_path  /var/cache/nginx  levels=1:2    keys_zone=NGINXCACHE:50m
                                    inactive={{ .Values.mirror.inactiveTime }}  max_size={{ .Values.mirror.maxCacheSize }};
    server {
      listen 8080;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      {{ range .Values.mirror.sites }}
      location {{ .path }} {
        proxy_pass        {{ .source }};
        proxy_redirect     off;
        proxy_set_header   Host             $http_host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_cache            NGINXCACHE;
        proxy_cache_valid      200  {{ .cacheValid }};
        proxy_cache_use_stale  error timeout invalid_header updating
                                  http_500 http_502 http_503 http_504;
      }
      {{ end }}
    }