apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: project-template-patch
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    project-template-patch:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: Project
        name: cluster
      patchTemplate: |
        spec:
          projectRequestTemplate:
            name: project-request
      patchType: application/merge-patch+json