apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: label-default-ns
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    label-default-ns-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Namespace
        name: default
      patchTemplate: |
        metadata:
          labels:
            network.openshift.io/policy-group: ingress
      patchType: application/merge-patch+json