apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-alertmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
  - targetObjectRef:
      apiVersion: v1
      kind: Secret
      name: alertmanager-main
      namespace: openshift-monitoring
    patchTemplate: |
      metadata:
        annotations:
          sealedsecrets.bitnami.com/managed: "true"
    id: patch-alertmanager