apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-alertmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-alertmanager:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: alertmanager-main
        namespace: openshift-monitoring
      patchTemplate: |
        metadata:
          annotations:
            sealedsecrets.bitnami.com/managed: "true"