apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-alertmanager
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    - targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: alertmanager-main
        namespace: openshift-monitoring
      patchTemplate: |
        metadata:
          annotations:
            sealedsecrets.bitnami.com/managed: "true"
      id: patch-alertmanager