apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  encryptedData:
    alertmanager.yaml: {{ .Values.alertmanager.config }}
  template:
    metadata:
      name: alertmanager-main
      namespace: openshift-monitoring