apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-argocd-rbac
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-argocd-rbac:
      targetObjectRef:
        apiVersion: argoproj.io/v1alpha1
        kind: ArgoCD
        name: {{ .Values.argocd.name }}
        namespace: {{ .Values.argocd.namespace }}
      patchTemplate: |
        spec:
          rbac:
            defaultPolicy: '{{ .Values.argocd.rbac.defaultPolicy }}'
            policy: |
              {{- range .Values.argocd.rbac.policies }}
              {{ . }}
              {{- end }}
      patchType: application/merge-patch+json
