apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-argocd-rbac
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    - targetObjectRef:
        apiVersion: argoproj.io/v1alpha1
        kind: ArgoCD
        name: {{ .Values.argocd.name }}
        namespace: {{ .Values.argocd.namespace }}
      patchTemplate: |
        spec:
          rbac:
            policy: 'g, Gepaplexx, role:admin'
      patchType: application/merge-patch+json
      id: patch-argocd-rbac