apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-argocd-ns
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    patch-argocd-ns:
      targetObjectRef:
        apiVersion: v1
        kind: Namespace
        name: {{ .Values.argocd.name }}
      patchTemplate: |
        metadata:
          annotations:
            openshift.io/node-selector: ""
      patchType: application/merge-patch+json