{{- if .Values.argocd.workflowrepository.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workflow-repository
  namespace: openshift-gitops
spec:
  encryptedData:
    sshPrivateKey: {{ .Values.argocd.workflowrepository.sshPrivateKey }}
    username: {{ .Values.argocd.workflowrepository.username }}
  template:
    data:
      name: {{ .Values.argocd.workflowrepository.secretName }}
      url: {{ .Values.argocd.workflowrepository.url}}
      insecure: "true"
      type: "git"
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository

{{- end -}}