{{- if .Values.argocd.workflowrepository.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-argocd-cm
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    patch-argocd-cm:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: argocd-cm
        namespace: {{ .Values.argocd.namespace }}
      patchTemplate: |
        data:
          repositories: |
            - url: {{ .Values.argocd.workflowrepository.url }}
              type: git
              usernameSecret:
                name: {{ .Values.argocd.workflowrepository.secretName }}
                key: username
              sshPrivateKeySecret:
                name: {{ .Values.argocd.workflowrepository.secretName }}
                key: sshPrivateKey
              insecure: true
      patchType: application/merge-patch+json
{{- end }}