apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}'
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-keycloak-instance.labels" . | nindent 4 }}
spec:
  hostname: {{  .Values.ingress.hostname }}
  instances: {{ .Values.replicas }}
  serverConfiguration:
    - name: features-disabled
      value: "{{ .Values.features.disabled }}"
    - name: features
      value: "{{ .Values.features.enabled }}"
    - name: health-enabled
      value: 'true'
    - name: metrics-enabled
      value: 'true'
  {{- if .Values.persistence.enabled }}
    - name: db
      value: postgres
    - name: db-url-host
      value: {{ .Values.postgresql.fullnameOverride }}
    - name: db-username
      secret:
        name: '{{ include "gp-keycloak-instance.fullname" . }}'
        key: username
    - name: db-password
      secret:
        name: '{{ include "gp-keycloak-instance.fullname" . }}'
        key: password
  {{- end }}
  tlsSecret: '{{ include "gp-keycloak-instance.fullname" . }}'
