apiVersion: v1
kind: Service
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}-service-metrics'
  labels:
    metrics-service: sso
spec:
  selector: # This selector will cause problems when multiple keycloak instances are within one namespace!!!! KC-Operator causes the problem because Pods are not properly labeled
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  ports:
    - name: metrics
      protocol: TCP
      port: 8443
      targetPort: 8443