apiVersion: v1
kind: Service
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}-service-metrics'
  label:
    metrics-service: sso
spec:
  selector:
    {{- include "gp-keycloak-instance.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: 8443
      targetPort: 8443