apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}'
spec:
  endpoints:
    - interval: 5s
      port: metrics
      scheme: https
      tlsConfig:
        ca:
          secret:
            name: '{{ include "gp-keycloak-instance.fullname" . }}-tls'
            key: tls.crt
            optional: false
        serverName: '{{ include "gp-keycloak-instance.fullname" . }}-service-metrics.{{ .Release.Namespace }}.svc'
  selector:
    matchLabels:
      metrics-service: sso