apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}'
spec:
  endpoints:
    - interval: 5s
      port: metrics
      scheme: https
  selector:
    matchLabels:
      metrics-service: sso