apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}'
  labels:
    {{- include "gp-keycloak-instance.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.ingress.hostname }}
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: '{{ include "gp-keycloak-instance.fullname" . }}'
  usages:
    - server auth
    - client auth
