{{- if .Values.argocd.addWorkflowRepository-}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflow-repository
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    username:
    sshPrivateKey: {{ .Values.argocd.repository.username }}
  template:
    metadata:
      name: workflow-repository
      namespace: {{ .Release.Namespace }}
{{- end -}}