kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.registry.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.registry.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.registry.name }}
  template:
    metadata:
      labels:
        deployment: {{ .Values.registry.name }}
    spec:
      containers:
      - name: registry
        image: {{ .Values.registry.image }}
        volumeMounts:
        - name: repo-vol
          mountPath: "/var/lib/registry"
        - name: registry-mirror-config
          mountPath: /etc/docker/registry
      volumes:
      - name: repo-vol
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: registry-mirror-config
        configMap:
          name: {{ .Values.config.name }}