apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ .Values.eventbus.name }}
  namespace: {{ .Release.Namespace }}
spec:
  jetstream:
    version: latest
    replicas: 3
    {{- if .Values.eventbus.persistence.enabled }}
    persistence:
      storageClassName: {{ .Values.eventbus.persistence.storageClassName }}
      accessMode: {{ .Values.eventbus.persistence.accessMode }}
      volumeSize: {{ .Values.eventbus.persistence.size }}
    {{- end }}