{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gp-bke-runtime-minimal-application.logical.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-bke-runtime-minimal-application.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gp-bke-runtime-minimal-application.logical.name" . }}
  {{- if or .Values.autoscaling.scaleOnCpu .Values.autoscaling.scaleOnMemory }}
  metrics:
  {{- end }}
  {{- if .Values.autoscaling.scaleOnCpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.cpuUtilization }}
  {{- end }}
  {{- if .Values.autoscaling.scaleOnMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.memoryUtilization }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 25
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
{{- end -}}