{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "gp-bke-runtime-minimal-application.labels" $ | nindent 4 }}
data:
  {{- range $item := .items }}
  {{ $item.key }}: {{ $item.value | quote | b64enc }}
  {{- end -}}
{{- end }}