apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    imageregistry.openshift.io: "true"
  name: {{ .Values.pvc.name }}
  namespace: openshift-image-registry
  labels:
      "alerts.k8s.io/kube-persistent-volume-filling-up=disabled"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}