apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  strategy: {{ .Values.strategy }}
  ingress:
    security: oauth-proxy
  storage:
    type: {{ .Values.storage.type }}
    {{- if eq .Values.storage.type "elasticsearch" }}
    elasticsearch:
      nodeCount: {{ .Values.elasticsearch.nodeCount }}
      redundancyPolicy: {{ .Values.elasticsearch.redundancyPolicy }}
    {{- if .Values.elasticsearch.indexCleaner.enabled }}
    {{- if .Values.elasticsearch.indexCleaner.enabled }}
    esIndexCleaner:
      enabled:  {{ .Values.elasticsearch.indexCleaner.enabled }}
      numberOfDays: {{ .Values.elasticsearch.indexCleaner.numberOfDays }}
      schedule: "{{ .Values.elasticsearch.indexCleaner.schedule }}"
    {{- end }}
    {{- end }}
    esRollover:
      schedule: "{{ .Values.elasticsearch.rollover.schedule }}"
    {{- end }}
    {{- if .Values.elasticsearch.options.serverUrl }}
    options:
      serverUrl: {{ .Values.elasticsearch.options.serverUrl }}
    {{- end}}