apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  strategy: {{ .Values.strategy }}
  ingress:
    security: oauth-proxy
  storage:
    type: {{ .Values.storage.type }}
    {{- if eq .Values.storage.type "elasticsearch" }}
    elasticsearch:
    {{- if not .Values.elasticsearch.useExisting }}
      nodeCount: {{ .Values.elasticsearch.nodeCount }}
      redundancyPolicy: {{ .Values.elasticsearch.redundancyPolicy }}
    {{- end }}
    {{- if .Values.elasticsearch.indexCleaner.enabled }}
    esIndexCleaner:
      enabled:  {{ .Values.elasticsearch.indexCleaner.enabled }}
      numberOfDays: {{ .Values.elasticsearch.indexCleaner.numberOfDays }}
      schedule: "{{ .Values.elasticsearch.indexCleaner.schedule }}"
    {{- end }}
    esRollover:
      schedule: "{{ .Values.elasticsearch.rollover.schedule }}"
    {{- end }}
    options:
      es:
    {{- if .Values.elasticsearch.useExisting }}
        server-urls:
        {{- range .Values.elasticsearch.options.serverurls }}
        - {{ . }}
        {{- end }}
    {{- end }}
        index-prefix: "{{ .Values.elasticsearch.options.indexprefix}}"
        tls.enabled: "true"
        tls.ca: /tls/admin-ca
        tls.cert: /tls/admin-cert
        tls.key: /tls/admin-key
  collector:
    resources:
      requests:
        memory: "{{ .Values.collector.requests.memory }}"
        cpu: "{{ .Values.collector.requests.cpu }}"
      limits:
        memory: "{{ .Values.collector.limits.memory }}"
        cpu: "{{ .Values.collector.limits.cpu }}"
    replicas: {{ .Values.collector.replicas }}
  volumeMounts:
    - name: es-tls
      mountPath: /tls
  volumes:
    - name: es-tls
      secret:
        secretName: elasticsearch