apiVersion: v1
data:
  tls.crt: {{ .Values.certificate }}
  tls.key: {{ .Values.key }}
kind: Secret
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.labels }}
  labels:
  {{- range $key, $value := .Values.labels }}
  {{- $key | nindent 4}}: {{ $value }}
  {{- end }}
  {{- end }}
type: kubernetes.io/tls