# Default values for http-mirror.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: "stable"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: openshift.infra.gepaplexx.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - openshift.infra.gepaplexx.com
      secretName: openshift-mirror

storageClassName: longhorn

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

mirror:
  maxCacheSize: 20g
  inactiveTime: 90d
  sites:
    - source: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/
      path: /
      cacheValid: 90d
    - source: https://mirror.openshift.com/icons/
      path: /icons
      cacheValid: 90d

nodeSelector: {}

tolerations: []

affinity: {}
