kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s2i-{{ .Values.applicationName }}-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
  volumeMode: Filesystem
