{{- if (eq .Values.project.create true)}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default "default" .Values.project.name }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
...
{{- end }}