{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-{{ include "gp-bke-runtime-minimal-application.fullname" . }}
  labels:
    {{- include "gp-bke-runtime-minimal-application.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: svc-{{ include "gp-bke-runtime-minimal-application.fullname" . }}
    weight: 100
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
{{- end }}
{{- end }}