# Default values for gp-bke-runtime-minimal-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# metadata.name: [RELEASE-NAME]-[nameOverride]
# metadata.label.app.kubernetes.io/name: [nameOverride]
nameOverride: ""

# metadata.name: [fullnameOverride]
# metadata.label.app.kubernetes.io/name: gp-bke-runtime-minimal-application
fullnameOverride: ""

image:
  # The name of the image to be used, e.g. image-registry.openshift-image-registry.svc.cluster.local:5000/example-project/example-backend
  name: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

ports: {}
  # - name: http
  #   containerPort: 8080
  #   protocol: TCP

podAnnotations: {}
  # annotation1: value1
  # annotation2: value2

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

route:
  # Deploy a route for this deployment?
  enabled: true
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge

livenessProbe:
  enabled: false
  path: "" # default is /

readinessProbe:
  enabled: false
  path: "" # default is /

# Define environment variables for the pod
env: {}

resources:
  limits:
    cpu: 750m
    memory: 800Mi
  requests:
    cpu: 250m
    memory: 400Mi