#https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-the-monitoring-stack
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: {{ .Values.clusterMonitoring.enableUserWorkload }}
    prometheusOperator:
      {{ include "infranodes.enabled" . }}
    prometheusK8s:
      {{ include "infranodes.enabled" . }}
      retention: {{ .Values.clusterMonitoring.prometheusK8s.retention }}
      resources:
        requests:
          cpu: {{ .Values.clusterMonitoring.prometheusK8s.resources.requests.cpu }}
          memory: {{ .Values.clusterMonitoring.prometheusK8s.resources.requests.memory }}
        limits:
          cpu: {{ .Values.clusterMonitoring.prometheusK8s.resources.limits.cpu }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.clusterMonitoring.prometheusK8s.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.clusterMonitoring.prometheusK8s.storageSize }}
    alertmanagerMain:
      {{ include "infranodes.enabled" . }}
      resources:
        requests:
          memory: {{ .Values.clusterMonitoring.alertmanagerMain.resources.requests.memory }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.clusterMonitoring.alertmanagerMain.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.clusterMonitoring.alertmanagerMain.storageSize }}
    kubeStateMetrics:
      {{ include "infranodes.enabled" . }}
    openshiftStateMetrics:
      {{ include "infranodes.enabled" . }}
    grafana:
      enabled: false # https://docs.openshift.com/container-platform/4.10/monitoring/accessing-third-party-monitoring-uis-and-apis.html#accessing-third-party-monitoring-uis
      {{ include "infranodes.enabled" . }}
    telemeterClient:
      {{ include "infranodes.enabled" . }}
    k8sPrometheusAdapter:
      {{ include "infranodes.enabled" . }}
    thanosQuerier:
      {{ include "infranodes.enabled" . }}
