apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    {{- if .Values.infranodes.enabled }}
    {{- .Files.Get "files/infraconfig.yaml"| nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/config.yaml" | nindent 4 }}
    {{- end }}