apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-monitoring-rules
  namespace: openshift-monitoring
spec:
  groups:
    - name: pvc.monitoring.rules
      rules:
        - alert: PersistentVolumeClaimNearlyFullWarning
          annotations:
            description: Das PersistentVolume claimed von {{`{{ $labels.persistentvolumeclaim }}`}} im Namespace {{`{{ $labels.namespace }}`}} ist mehr als 80% voll. Aktuell sind {{`{{ $value | humanizePercentage }}`}} verfügbar.
            summary: PersistentVolumeClaim zu 80% voll.
          expr: |
            (kubelet_volume_stats_available_bytes{job="kubelet",metrics_path="/metrics"} /
            kubelet_volume_stats_capacity_bytes{job="kubelet",metrics_path="/metrics"}) < 0.2 and
            kubelet_volume_stats_used_bytes{job="kubelet",metrics_path="/metrics"} > 0
          for: 20m
          labels:
            severity: warning
            monitoring: pvc
        - alert: PersistentVolumeClaimAlmostFullAlert
          annotations:
            description: Das PersistentVolume claimed von {{`{{ $labels.persistentvolumeclaim }}`}} im Namespace {{`{{ $labels.namespace }}`}} ist mehr als 90% voll. Aktuell sind {{`{{ $value | humanizePercentage }}`}} verfügbar.
            summary: PersistentVolumeClaim zu 90% voll.
          expr: |
            (kubelet_volume_stats_available_bytes{job="kubelet",metrics_path="/metrics"} /
            kubelet_volume_stats_capacity_bytes{job="kubelet",metrics_path="/metrics"}) < 0.1 and
            kubelet_volume_stats_used_bytes{job="kubelet",metrics_path="/metrics"} > 0
          for: 20m
          labels:
            severity: critical
            monitoring: pvc
