{{- if .Values.autoUnseal.creds -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gcp-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-hashicorp-vault.labels" . | nindent 4 }}
spec:
  encryptedData:
    creds.json: {{ .Values.autoUnseal.creds }}
  template:
    data: null
    metadata: {}
{{- end -}}