{{- if .Values.autoUnseal.creds -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gcp-sealedsecret
  labels:
    {{- include "gp-hashicorp-vault.labels" . | nindent 4 }}
spec:
  encryptedData:
    creds.json: {{ .Values.autoUnseal.creds }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ (index .Values.vault.server.volumes 1).secret.secretName }}
      namespace: {{ .Release.Namespace }}
{{- end -}}