kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-hashicorp-vault.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: vault-ui
    weight: 100
  port:
    targetPort: http
