apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-console
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    patch-console:
      targetObjectRef:
        apiVersion: operator.openshift.io/v1
        kind: Console
        name: cluster
      patchTemplate: |
        spec:
          customization:
            customLogoFile:
              key: console-custom-logo.png
              name: custom-logo
          customProductName: {{ .Values.productName }}
      patchType: application/merge-patch+json