apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secretmessage
    {{- include "gp-secretmessage.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: secretmessage
      {{- include "gp-secretmessage.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secretmessage
        {{- include "gp-secretmessage.labels" . | nindent 8 }}
    spec:
      containers:
      - image: ghcr.io/fhochleitner/secretmessage:1.0
        env:
          - name: SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS
            value: ":{{ .Values.ports.http }}"
          - name: SUPERSECRETMESSAGE_HTTPS_BINDING_ADDRESS
            value: ":{{ .Values.ports.https }}"
          - name: SUPERSECRETMESSAGE_HTTPS_REDIRECT_ENABLED
            value: "{{ .Values.secure.redirectEnabled }}"
          - name: SUPERSECRETMESSAGE_TLS_AUTO_DOMAIN
            value: "{{ .Values.secure.tlsAutoDomain }}"
        imagePullPolicy: IfNotPresent
        name: secretmessage
        ports:
        - containerPort: {{ .Values.ports.http }}
          protocol: TCP
        - containerPort: {{ .Values.ports.https }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
