apiVersion: v1
kind: Service
metadata:
  labels:
    app: secretmessage
    {{- include "gp-secretmessage.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.ports.http }}
    name: http
    protocol: TCP
    targetPort: {{ .Values.ports.http }}
  - port: {{ .Values.ports.https }}
    name: https
    protocol: TCP
    targetPort: {{ .Values.ports.https }}
  selector:
    app: secretmessage
    {{- include "gp-secretmessage.labels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
