apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    kubernetes.io/metadata.name: external-secrets-operator
    openshift.io/cluster-monitoring: "true"
  name: gp-eso
spec: {}