apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}-og
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gp-external-secrets-operator.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    {{- include "gp-external-secrets-operator.labels" . | nindent 4 }}
  name: external-secrets-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: "{{ .Values.subscription.channel }}"
  installPlanApproval: "{{ .Values.subscription.installPlanApproval }}"
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
