apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: gp-eso
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 256Mi
  certController:
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 100m
        memory: 256Mi
  webhook:
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 96Mi
      limits:
        cpu: 100m
        memory: 256Mi