apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: external-secrets-og
  namespace: gp-eso
spec: {}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: gp-eso
spec:
  channel: "{{ .Values.subscription.channel }}"
  installPlanApproval: "{{ .Values.subscription.installPlanApproval }}"
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
