apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-operator-monitoring
  labels:
    {{- include "gp-external-secrets-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - servicemonitors
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch