apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-operator
  labels:
    {{- include "gp-external-secrets-operator.labels" . | nindent 4 }}
roleRef:
  name: external-secrets-operator
  kind: ClusterRole
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: external-secrets-operator-controller-manager
    namespace: gp-eso
