# Default values for gp-bke-argocd-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argocd:
  application:
    # Name of the ArgoCD Application
    name: 
    source: {}

    destination:
      # The namespace in which the application is deployed, default is Release.Namespace
      namespace: ""
      createNamespace: true

    syncPolicy:
      prune: true
      selfHeal: true

  project:
    # true = create new/override existing project, false = use existing project, fail if there is no project found
    create: false
    name: "default"

  plugins:
    vault:
      enable: false
      k8Role: "default"
      url: 'http://vault.vault.svc.cluster.local:8200'