{{- if .Values.pipelineRun.create -}}
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-{{ .Values.applicationName }}-pipeline-run-{{ .Release.Revision }}
spec:
  pipelineRef:
    name: s2i-{{ .Values.applicationName }}-pipeline
  params:
    - name: application
      value: {{ .Values.applicationName }}
    - name: source-repo-url
      value: {{ .Values.pipelineRun.sourceRepo }}
    - name: source-revision
      value: {{ .Values.pipelineRun.sourceRevision }}
    - name: image-registry
      value: {{ .Values.pipelineRun.imageRegistry }}
    - name: image-repository
      value: {{ .Values.pipelineRun.imageRepository | default .Release.Namespace | quote }}      
    - name: builder-image
      value: {{ .Values.pipelineRun.builderImage | quote }}
    - name: context-dir
      value: {{ .Values.pipelineRun.contextDir | default . | quote}}
  workspaces:
  - name: s2i-{{ .Values.applicationName }}-source
    persistentvolumeclaim:
      claimName: s2i-{{ .Values.applicationName }}-source-pvc
{{- end }}