apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonarqube-proxy
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sonarqube-proxy-binding
roleRef:
  kind: ClusterRole
  name: sonarqube-proxy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sonarqube.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---