apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-sonarqube-proxy-binding
roleRef:
  kind: ClusterRole
  name: gp-auth-proxy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sonarqube.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---