name: Publish Helm Chart

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Publish Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GP_HELM_REPO }}
        charts_dir: .
        charts_url: https://gepaplexx.github.io/gp-helm-charts/
        owner: gepaplexx
        repository: gp-helm-charts
        branch: main