---
name: Build and push Helm charts

'on':
  push:
    branches:
      - 'develop'
    tags-ignore:
      - '**'

jobs:
  release:
    runs-on: [self-hosted, Linux, x64, environment-central]
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://gepaplexx.github.io/gp-helm-charts/
          owner: gepaplexx
          repository: gp-helm-charts
          branch: main
