---
name: Helm Release

'on':
  workflow_dispatch:
  push:
    branches: 
      - 'develop'
    tags-ignore:
      - '**'

jobs:
  release-helm-charts:
    name: "Release Helm Chart"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[helm release]')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Publish Pull-Through-Cache Chart
        uses: stefanprodan/helm-gh-pages@master
        with: 
          token: ${{ secrets.PAT }}
          charts_dir: .
          charts_url: https://docs.gepaplexx.com/gp-helm-charts/
          owner: gepaplexx
          repository: gp-helm-charts
          branch: main
...