---
name: Build and push Helm charts

'on':
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - name: Build Subchart dependencies
        run: |
          bin/update-helm-dependencies.sh

      - name: Lint Helm
        run: |
          helm lint \
             ./bke-runtime/*/. \
             ./bke-development/*/. \
             ./infra/*/. \
             ./day-2-operations/*/. \
             ./gp-workload/*/. \
             ./gp-apps/*/.

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [bke-runtime, bke-development, infra, gp-workload, gp-apps]
    needs:
      - lint-helm
    steps:
      - uses: actions/checkout@v2
      - name: Publish ${{matrix.dir }} Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.PAT }}
          charts_dir: ./${{ matrix.dir }}
          charts_url: https://gepaplexx.github.io/gp-helm-charts/
          owner: gepaplexx
          repository: gp-helm-charts
          branch: main

  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - release
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/fhochleitner/logos/raw/master/helm.png
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''
