apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.solvers.secretName }}
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: {{ .Values.solvers.secretAccessKey }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.solvers.secretName }}
      namespace: cert-manager
