apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: "{{ .Values.clusterlogging.subscription.channel }}"
  name: cluster-logging
  installPlanApproval: "{{ .Values.clusterlogging.subscription.installPlanApproval }}"
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
