apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-{{ .Values.applicationName }}-pipeline
spec:
  description: |
    This pipeline will clone a given repository revision, build a Quarkus application,
    pushing the final image into the Openshift internal registry
  params:
  - name: application
    type: string
    description: Name for the application 
  - name: source-repo-url
    type: string
    description: The git repository URL to clone from.
  - name: source-revision
    type: string
    description: The git revision to clone.
  - name: short-source-revision
    type: string
    description: Short commit id
  - name: image-registry
    type: string
    description: Image registry
  - name: image-repository
    type: string
    description: Image repository within image-registry the image will be pushed to
  - name: dockerfile
    type: string
    description: Dockerfile location used to build the final image
  - name: contextdir
    type: string
    description: Path to subproject inside the repo
  workspaces:
  - name: source
  - name: maven-settings
  tasks:
  - name: fetch-source-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.source-repo-url)
    - name: revision
      value: $(params.source-revision)
    - name: subdirectory
      value: $(params.source-revision)
    - name: deleteExisting
      value: "true"
  - name: maven-build-and-test
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - fetch-source-repository
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value: ["-f", "$(params.source-revision)/$(params.contextdir)/pom.xml", "clean", "package"] 
      - name: MAVEN_IMAGE
        value: {{ .Values.pipeline.mvn.image }}
  - name: image-build-and-push
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: $(params.image-registry)/$(params.image-repository)/$(params.application):$(params.source-revision)
      - name: CONTEXT
        value: $(workspaces.source.path)/$(params.source-revision)/$(params.contextdir)
      - name: DOCKERFILE
        value: $(params.dockerfile)
    workspaces: 
      - name: source
        workspace: source 
    runAfter:
      - maven-build-and-test