apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-{{ .Values.applicationName | default .Release.Name }}-pipeline
spec:
  description: |
    This pipeline will clone a given repository revision, build a Quarkus application,
    pushing the final image into the Openshift internal registry
  params:
  - name: application
    type: string
    description: 'name of the application'
    default: {{ .Values.applicationName | default .Release.Name }}
  - name: source-repo-url
    type: string
    description: 'git repository URL to clone from'
    default: {{ .Values.sourceRepo }}
  - name: source-revision
    type: string
    description: 'git revision to checkout (branch, tag, sha, ref…)'
    default: {{ .Values.sourceRevision }}
  - name: version
    type: string
    description: 'tag of the final image'
  - name: image-registry
    type: string
    description: Image registry
    default: {{ .Values.imageRegistry }}
  - name: image-repository
    type: string
    description: 'image repository within image registry the image will be pushed to'
    default: {{ .Values.imageRepository | default .Release.Namespace | quote }}
  - name: dockerfile
    type: string
    description: 'dockerfile wich will be used to build the image'
    default: {{ .Values.dockerfile | default './src/main/docker/Dockerfile.jvm' }}
  - name: contextdir
    type: string
    description: 'path to a subproject inside the repo'
    default: {{ .Values.contextdir }}
  workspaces:
  - name: source
  - name: maven-settings
  tasks:
  - name: fetch-source-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.source-repo-url)
    - name: revision
      value: $(params.source-revision)
    - name: subdirectory
      value: $(params.source-revision)
    - name: deleteExisting
      value: "true"
  - name: maven-build-and-test
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - fetch-source-repository
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: maven-settings
    params:
      - name: GOALS
        value: ["-f", "$(params.source-revision)/$(params.contextdir)/pom.xml", "clean", "package"] 
      - name: MAVEN_IMAGE
        value: {{ .Values.pipeline.mvn.image }}
  - name: image-build-and-push
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: $(params.image-registry)/$(params.image-repository)/$(params.application):$(params.version)
      - name: CONTEXT
        value: $(workspaces.source.path)/$(params.source-revision)/$(params.contextdir)
      - name: DOCKERFILE
        value: $(params.dockerfile)
    workspaces: 
      - name: source
        workspace: source 
    runAfter:
      - maven-build-and-test