kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
#  storageClassName: ${STORAGE_CLASS}
  volumeMode: Filesystem
