{{- if .Values.createInitialRun -}}
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{ .Values.applicationName | default .Release.Name }}-pipeline-run-{{ .Release.Revision }}
spec:
  pipelineRef:
    name: build-and-push-{{ .Values.applicationName }}-pipeline
  params:
    - name: application
      value: {{ .Values.applicationName }}
    - name: source-repo-url
      value: {{ .Values.sourceRepo }}
    - name: source-revision
      value: {{ .Values.sourceRevision }}
    - name: short-source-revision
      value: "{{ .Values.shortSourceRevision }}"
    - name: dockerfile
      value: {{ .Values.dockerfile | default "./src/main/docker/Dockerfile.jvm" | quote }}
    - name: image-registry
      value: {{ .Values.imageRegistry }}
    - name: image-repository
      value: {{ .Values.imageRepository | default .Release.Namespace | quote }}
    - name: contextdir
      value: {{ .Values.contextdir }}
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: source-pvc 
  - name: maven-settings
    configMap: 
       name: maven
{{- end }}