google:
  enable: false
  k8secretName: google-oauth-secret
  clientId: {}
  restrDomain: {}
  clientSecret: {}

git:
  enable: false
  k8secretName: github-oauth-secret
  clientId: {}
  restrOrgs: []
  clientSecret: {}

htpasswd:
  enable: false
  k8secretName: htpass-secret
  data: {}

ldap:
  enable: false
  k8secretName: ldap-secret
  bindPassword: changeMe
  bindDn: "CN=Username,OU=Users,OU=Org,DC=domain,DC=tld"
  ldapUrl: "ldap://host/OU=Users,OU=Org,DC=domain,DC=tld?uid"