google:
  enable: true
  k8secretName: google-oauth-secret
  clientId: {}
  restrDomain: {}
  clientSecret: {}

git:
  enable: true
  k8secretName: github-oauth-secret
  clientId: {}
  restrOrgs: []
  clientSecret: {}

htpasswd:
  enable: true
  k8secretName: {}
  data: {}