google:
  enable: false
  k8secretName: google-oauth-secret
  clientId: {}
  restrDomain: {}
  clientSecret: {}

git:
  enable: false
  k8secretName: github-oauth-secret
  clientId: {}
  restrOrgs: []
  clientSecret: {}

htpasswd:
  enable: false
  k8secretName: htpass-secret
  data: {}

ldap:
  enable: false
  k8secretName: ldap-secret
  bindPassword: changeMe
  bindDn: "CN=Username,OU=Users,OU=Org,DC=domain,DC=tld"  # SealedSecret encrypted
  ldapUrl: "ldap://host/OU=Users,OU=Org,DC=domain,DC=tld?cn?sub" # SealedSecret encrypted
  usersQuery: "OU=Groups,DC=domain,DC=tld" # SealedSecret encrypted
  syncFilter: ""
  groupMappings:
#    "CN=OC Editors,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local": ldap-editor
#    "CN=OC_Administrators,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local": ldap-admin
#    "CN=OC_Readonly_Users,OU=Groups,OU=GEPAPLEXX,DC=gp,DC=local": ldap-ro